name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run python
        run: |
          pip3 install requests
          pip3 install bs4
          pip3 install json
          # python3 crawl_chinanews.py
          ls
          cd 阿里云盘吧爬虫
          ls
          python3 tiebaspider.py
      

